openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/register:
    post:
      summary: Регистрация
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Registration is successful'
                properties:
                  message:
                    type: string
                    example: 'Registration is successful'
        422:
          description: 'validation fail'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: validation.email
                  errors:
                    email:
                      - validation.email
                properties:
                  message:
                    type: string
                    example: validation.email
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - validation.email
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Имя. validation.max.'
                  example: Иван
                last_name:
                  type: string
                  description: 'Фамилия. validation.max.'
                  example: Иванов
                email:
                  type: string
                  description: 'Email. validation.email validation.max.'
                  example: ivan.ivanov@test.org
                password:
                  type: string
                  description: 'Пароль. validation.max.'
                  example: test
              required:
                - first_name
                - last_name
                - email
                - password
      security: []
  /api/v1/login:
    get:
      summary: Авторизация
      operationId: ''
      description: 'После пройденной аутентификации создается accessToken'
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Authorization is successful'
                properties:
                  message:
                    type: string
                    example: 'Authorization is successful'
        403:
          description: 'invalid email or password'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid email or password'
                properties:
                  message:
                    type: string
                    example: 'Invalid email or password'
        422:
          description: 'validation fail'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: validation.email
                  errors:
                    email:
                      - validation.email
                properties:
                  message:
                    type: string
                    example: validation.email
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - validation.email
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Email. validation.email validation.max.'
                  example: ivan.ivanov@test.org
                password:
                  type: string
                  description: 'Пароль. validation.max.'
                  example: test
              required:
                - email
                - password
      security: []
  /api/v1/users:
    get:
      summary: 'Список пользователей'
      operationId: ''
      description: "Отдается порционно по 20 пользователей.\nДля получения следующих страниц, необходимо передать `page` с номером страницы."
      parameters:
        -
          in: query
          name: page
          description: 'Номер страницы.'
          example: '2'
          required: false
          schema:
            type: string
            description: 'Номер страницы.'
            example: '2'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    first_name: Иван
                    last_name: Иванов
                    email: ivan.ivanov@test.org
      tags:
        - Endpoints
  /api/v1/chats:
    get:
      summary: 'Получение списка чатов'
      operationId: ''
      description: "Отдается порционно по 20 чатов.\nДля получения следующих страниц, необходимо передать `page` с номером страницы"
      parameters:
        -
          in: query
          name: page
          description: 'Номер страницы.'
          example: '2'
          required: false
          schema:
            type: string
            description: 'Номер страницы.'
            example: '2'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: 'Иван Иванов'
                    created_at: '2024-05-16T19:09:48.000000Z'
                    updated_at: '2024-05-16T19:09:48.000000Z'
                    users:
                      -
                        id: 1
                        first_name: Иван
                        last_name: Иванов
                        email: ivan.ivanov@test.org
                      -
                        id: 2
                        first_name: Николай
                        last_name: Николаев
                        email: nikolay.nikolayev@test.org
      tags:
        - Endpoints
    post:
      summary: 'Создание чата'
      operationId: ''
      description: "Создается чат с передаваемым пользователем, если его не существует.\n\nДля создания чата с пользователем, необходимо в параметрах передать `user_id`."
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Chat created'
                properties:
                  message:
                    type: string
                    example: 'Chat created'
        404:
          description: 'user not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not found'
                properties:
                  message:
                    type: string
                    example: 'User not found'
        409:
          description: 'chat with yourself'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'It is impossible to create a chat with yourself'
                properties:
                  message:
                    type: string
                    example: 'It is impossible to create a chat with yourself'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ''
                  example: 5
              required:
                - user_id
  '/api/v1/chats/{chatId}/messages':
    get:
      summary: 'Получение списка сообщений'
      operationId: ''
      description: "Отдается порционно по 20 чатов.\nДля получения следующих страниц, необходимо передать `page` с номером страницы"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 6
                    chat_id: 2
                    text: test
                    created_at: '2024-05-16T20:35:59.000000Z'
                    updated_at: '2024-05-16T20:35:59.000000Z'
        404:
          description: 'chat not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Chat not found'
                properties:
                  message:
                    type: string
                    example: 'Chat not found'
      tags:
        - Endpoints
    post:
      summary: 'Создание сообщения'
      operationId: ''
      description: "Создается сообщение в чате.\nНеобходимо указать в URI `chatId` и передать `text`в теле запроса."
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Message created'
                properties:
                  message:
                    type: string
                    example: 'Message created'
        404:
          description: 'chat not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Chat not found'
                properties:
                  message:
                    type: string
                    example: 'Chat not found'
        422:
          description: 'validation fail'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: validation.text
                  errors:
                    text:
                      - validation.text
                properties:
                  message:
                    type: string
                    example: validation.text
                  errors:
                    type: object
                    properties:
                      text:
                        type: array
                        example:
                          - validation.text
                        items:
                          type: string
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: validation.max.
                  example: ktqehjgxfnyhe
              required:
                - text
    parameters:
      -
        in: path
        name: chatId
        description: ''
        example: '0'
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
